#!/bin/bash

# Creates a new Heroku app and adds it as a git remote.
# The environment name could be staging, production, etc
#
# Usage: create-heroku-app <app name> <environment name> <team>

APP=$1
ENV=$2
TEAM=$3


fail() {
  echo "ERROR: $1"
  exit -1
}

message() {
echo
echo "👉  $1"
echo
}

heroku_command() {
  message "Running heroku $*"
  heroku $* -r $ENV || fail
}


if [ -z "$APP" ] ; then
  fail "Missing Heroku app name parameter"
fi

if [ -z "$ENV" ] ; then
  fail "Missing Heroku remote (environment name) parameter"
fi

if [ -z "$TEAM" ] ; then
  fail "Missing Heroku team name parameter"
fi

heroku apps:create --buildpack https://github.com/okgrow/meteor-buildpack-horse.git -r $ENV $APP --team $TEAM || fail
heroku_command addons:create mongolab
heroku_command config:add ROOT_URL="https://$APP.herokuapp.com"
heroku_command config:add ENV=$ENV
heroku_command labs:enable http-session-affinity

heroku_command addons:create logentries:le_tryit
heroku_command addons:create mailgun:starter
heroku_command addons:create scheduler:standard

message "To make this your default Heroku environment: git config heroku.remote $ENV"
